### ISSUE TITLE
Nested arrays in commands array produce an error

### ISSUE THREAD

**Issue by wuhhh** [putyourlightson/craft-blitz-shell#1]
### Describe the bug
The format for deployer settings => commands in your README looks like this:

```
'deployerSettings' => [
   'commands' => [
        ['cp -r ~/mysite.com/web/cache/blitz ~/remote'],
        ['cp -r ~/mysite.com/web/cache/blitz ~/remote'],
        ['cp -r ~/mysite.com/web/cache/blitz ~/remote'],
    ],
],
```

However, following this syntax results in an error:

`Argument 1 passed to Symfony\Component\Process\Process::fromShellCommandline() must be of the type string, array given`

Removing the inner array worked for me, so I'm not sure if this is a simple typo:

```
'deployerSettings' => [
   'commands' => [
        'cp -r ~/mysite.com/web/cache/blitz ~/remote',
    ],
],
```

I only needed one command so I'm unsure if it would work to simply list further commands here inside the `commands` array. 

### Versions
- Plugin version: 1.0.0
- Craft version: 3.7.28

**Comment by bencroker** [comment]
Sorry for not responding sooner, this went under my radar, somehow.

This issue was fixed in version 1.1.0.
